name: 'LeRobot'

root: 'outputs/dataset/abd_collection'
repo_id: 'uhnam/abd'

fps: 5

features : {
    'observation.images.rgb.wrist': {
        "dtype": 'video',
        'shape': [480,640,3],
        'names': ['height', 'width', 'channels']
    },
    'observation.images.rgb.front': {
        "dtype": 'video',
        'shape': [480,640,3],
        'names': ['height', 'width', 'channels']
    },
    'observation.images.rgb.table': {
        "dtype": 'video',
        'shape': [480,640,3],
        'names': ['height', 'width', 'channels']
    },
     'action': {
        "dtype": 'float32',
        'shape': [7,],
        'names': None
    },
    'observation.state': {
        "dtype": 'float32',
        'shape': [7,],
        'names': None
    },
}