defaults:
  - env: real
  - task: pick_place
  - policy: vlm_checklist
  - vlm: gpt
  - dataset_recorder: LeRobot
  - train: bc
  - _self_

perception:
  url: "http://localhost:9877/inference"

motion_planner:
  smoothing: true

max_episodes: 1000
max_retries: 3
seed: 0

log_dir: outputs/logs/${now:%Y-%m-%d_%H-%M-%S}
